### ISSUE TITLE
Option for syn/quote

### ISSUE THREAD

**Issue by tjkirch** [llogiq/momo#10]
I appreciate the reasons for converting to watt, but if I have software that already includes syn/quote or whose compile time dominates that of syn/quote, it would be nice to use it rather than including watt and needing a wasm toolchain.

**Comment by dtolnay** [comment]
FWIW you don't need a wasm toolchain to use watt based macros. (But this is very unclear from the momo readme.)

Try it:

```toml
[package]
name = "demo"
version = "0.0.0"
edition = "2018"

[dependencies]
momo = "0.2"
```

```rust
use momo::momo;

#[momo]
fn demo<S: AsRef<str>>(arg: S) {
    println!("{}", arg);
}

fn main() {}
```
