### ISSUE TITLE
Marginal improvement on `-Zbuild_std`

### ISSUE THREAD

**Issue by Super-Pizza** [llogiq/momo#24]
I found a feature which can reduce the size marginally.

First, the initial config:
`~/.cargo/config,.toml`
```toml
[build]
rustflags="-C lto=true -C embed_bitcode=yes -Zdylib-lto -Zlocation-detail=none -C opt_level=z -C panic=abort -C codegen_units=1 -C strip=symbols -C target_cpu=native"
```

Now the interesting part:
```diff
cargo +nighlty build -Zbuild_std=std,panic-abort \
+  -Zbuild-std-features=compiler-builtins-mangled-names
```
This reduced the installation size of [`starship`](https://starship.rs) from 4,638KB to 4,501KB on my system.

# How?
I found this by looking at `cargo bloat`'s output and found many useless core functions there. The feature simply mangles these to make them "removable" by the linker.
